export const asignee = [
  {label: 'Shivansh Nayak', value: '1'},
  {label: 'Shiv Sagar', value: '2'},
  {label: 'Deep Prajapati', value: '3'},
  {label: 'Rutvik Thamar', value: '4'},
  {label: 'Viren Patadiya', value: '5'},
  {label: 'Manish Singh', value: '6'},
  {label: 'Yash Nandanve', value: '7'},
  {label: 'Parth Chauhan', value: '8'},
  {label: 'Colin Shah', value: '9'},
  {label: 'Kinjal Patel', value: '10'},
  {label: 'Dinesh Kachhot', value: '11'},
  {label: 'Lavesh Katariya', value: '12'},
  {label: 'Mihir', value: '13'},
  {label: 'Krupesh', value: '14'},
  {label: 'Jagat', value: '15'},
  {label: 'Nikhil Singh', value: '16'},
  {label: 'Juned Lanja', value: '17'},
  {label: 'Raj Bhatt', value: '18'},
  {label: 'Jenish Menpara', value: '19'},
];
